### PR TITLE
[PR]README of English Verison 

### PR DESCRIPTION
**Pull request by crazybber**
a english version for readme ,if necessary, an url can be put into your readme.

### CODE REVIEW

**Comment by palanjyan** [comment]
Thank you for your assistance in the development of the project. In the near future we will add your translation of README.md.
We are always open to suggestions.

**Comment by crazybber** [comment]
@palanjyan thank you.
i did some improving and refactoring to standardize the code and file style .
you guys could review it and check using it or not.

**Comment by crazybber** [comment]
@palanjyan 
i‘m using this library to support my coding work , so leaving this PR open .
you can review it any time maybe some idea will flash inside your mind , (●'◡'●)~~~.
of course ,if necessary ,you can close it.

**Comment by palanjyan** [comment]
@CrazyBBer 
 I will not close the project. I will do  the "merge pull request".

**Comment by crazybber** [comment]
i plan to maintain a modified version.

**Pull request closed without merging**
